version: '3.9'

services:
  jupyter:
    image: jupyter/scipy-notebook:python-3.10.6
    working_dir: '/ipynb'
    ports:
      - '8888:8888'
    restart: unless-stopped
    volumes:
      - ./:/work
